### PR TITLE
Update dependencies to address high sev vulnerabilities

### PR DESCRIPTION
**Pull request by vdamle**
* downstream builds that use this package fail due to high severity
vulnerabilities
* update gitignore to include package-lock.json and delete the file in
git

Verified that tests pass locally by running `npm test`

### CODE REVIEW

**Review by macfarla — COMMENTED** [review]
apologies for the delay on our end - this looks good except that we need the package-lock.json for the CI build process.

**Comment by vdamle** [comment]
thanks for the feedback, @macfarla . I've restored `package-lock.json` and looks like the CI build is passing now.

**Review by macfarla — APPROVED** [review]
LGTM

**Comment by macfarla** [comment]
Thanks for the contribution!

**Comment by vdamle** [comment]
@macfarla - Is there a timeline for when a release with the latest changes will be cut?

**Comment by macfarla** [comment]
@vdamle  0.11.0 released!

**Pull request merged**
